"""Add FK for created_by and updated_by

Revision ID: c9300ad69af6
Revises: 
Create Date: 2025-07-22 05:24:48.443631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9300ad69af6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.alter_column('events', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('events', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('events', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_foreign_key(None, 'events', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key(None, 'events', 'users', ['updated_by_id'], ['id'])
    op.drop_column('events', 'updated_by')
    op.drop_column('events', 'created_by')
    op.add_column('users', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['updated_by_id'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['created_by_id'], ['id'])
    op.drop_column('users', 'updated_by')
    op.drop_column('users', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'updated_by_id')
    op.drop_column('users', 'created_by_id')
    op.add_column('events', sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.alter_column('events', 'end_time',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('events', 'start_time',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('events', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('events', 'updated_by_id')
    op.drop_column('events', 'created_by_id')
    # ### end Alembic commands ###
